language: python
cache: pip
python:
  - "2.7"
env:
  matrix:
    - VAULT_VER="0.4.0"
    - VAULT_VER="0.4.1"
    - VAULT_VER="0.5.0"
    - VAULT_VER="0.5.1"
sudo: false
notifications:
  email:
    - simond@irrelevant.org
install:
  - "pip install -r requirements.txt"
  - "make ci"
before_script:
script: make test
