language: python
cache: pip
dist: trusty
python:
  - "2.7"
env:
  matrix:
    - VAULT_VER="0.4.1"
      ANSIBLE_VER="1.9.6"
    - VAULT_VER="0.5.0"
      ANSIBLE_VER="1.9.6"
    - VAULT_VER="0.5.1"
      ANSIBLE_VER="1.9.6"
    - VAULT_VER="0.5.3"
      ANSIBLE_VER="1.9.6"
    - VAULT_VER="0.6.0"
      ANSIBLE_VER="1.9.6"
    - VAULT_VER="0.6.4"
      ANSIBLE_VER="1.9.6"

    - VAULT_VER="0.4.1"
      ANSIBLE_VER="2.2"
    - VAULT_VER="0.5.0"
      ANSIBLE_VER="2.2"
    - VAULT_VER="0.5.1"
      ANSIBLE_VER="2.2"
    - VAULT_VER="0.5.3"
      ANSIBLE_VER="2.2"
    - VAULT_VER="0.6.0"
      ANSIBLE_VER="2.2"
    - VAULT_VER="0.6.4"
      ANSIBLE_VER="2.2"

sudo: false
notifications:
  email:
    - simond@irrelevant.org
install:
  - pip install -q ansible==$ANSIBLE_VER
  - "make ci"
before_script:
script: make test
