---

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  become: False
  vars_files:
    - ../group_vars/vault

  tasks:
    - include: test-vault-credentials.yml

    - name: Create secret
      vault_secret:
        token: "{{ vault_token }}"
        tls: off
        state: present
        secret: 'secret/foo1'
        key:
          user: username1
          pass: password1

    - name: Remove secret
      vault_secret:
        token: "{{ vault_token }}"
        tls: off
        state: absent
        secret: 'secret/foo1'

    - name: Remove secret (should be no changes)
      vault_secret:
        token: "{{ vault_token }}"
        tls: off
        state: absent
        secret: 'secret/foo1'
