---

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  become: False
  vars_files:
    - ../group_vars/vault

  tasks:
    - include: test-vault-credentials.yml

    - name: Create policy1
      vault_policy:
        token: "{{ vault_token }}"
        tls: off
        state: present
        policy_name: 'policy1'
        policy: 'path "sys/*" { policy = "deny" }'

    - name: Create policy2
      vault_policy:
        token: "{{ vault_token }}"
        tls: off
        state: present
        policy_name: 'policy2'
        policy: "{{ lookup('file', '../data/sample_policy') }}"

    - name: Remove policy1
      vault_policy:
        token: "{{ vault_token }}"
        tls: off
        state: absent
        policy_name: 'policy1'

    - name: Remove policy1 (should be no changes)
      vault_policy:
        token: "{{ vault_token }}"
        tls: off
        state: absent
        policy_name: 'policy1'

    - name: Remove policy2
      vault_policy:
        token: "{{ vault_token }}"
        tls: off
        state: absent
        policy_name: 'policy2'
